[package]
name = "prolog_parser"
version = "0.7.9"
authors = ["Mark Thom <markjordanthom@gmail.com>"]
repository = "https://github.com/mthom/prolog_parser"

[dependencies]
num = "0.2"
ordered-float = "0.5.0"

[lib]
path = "src/lib.rs"
